version: '3'
services:
  helloworld:
    image: leotodevops/helloworld
  web-nginx:
    image: leotodevops/mynginx:1.0
    ports:
    - "5001:80"
  web-python-flask:
    image: leotodevops/cat:1.0
    ports:
    - "5000:5000"

